### ISSUE TITLE
Hay un bug con las contraint

### ISSUE THREAD

**Issue by JahelCuadrado** [Ufransa/newsScrap#3]
Se vuelven locas!!!

![image](https://user-images.githubusercontent.com/81108487/196010530-cc11f2a8-d739-4161-a935-a17dbdaf52fd.png)

**Comment by Ufransa** [comment]
Ahh... corregido. Gracias bestia, tanque, titán...

**Comment by JahelCuadrado** [comment]
> Ahh... corregido. Gracias bestia, tanque, titán...

No lo has hecho, no mientas!! 🤓💩
